name: Macros

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - uses: dart-lang/setup-dart@v1
    - run: dart pub get
    - run: dart run build_runner build --delete-conflicting-outputs
    - uses: peter-evans/create-pull-request@v7
      if: github.event_name != 'pull_request'
      with:
        title: 'Regenerate macros'
        commit-message: 'Regenerate macros'
        add-paths: '**/*.g.dart'
        branch: regenerate/macros
        delete-branch: true
    - run: |
        git diff > lib_src_macros.g.dart.diff
        [ -s lib_src_macros.g.dart.diff ] || rm lib_src_macros.g.dart.diff
    - uses: actions/upload-artifact@v4
      with:
        name: lib_src_macros.g.dart.diff
        path: lib_src_macros.g.dart.diff
        if-no-files-found: ignore
    - run: ./.github/scripts/check-outdated-files.sh
